/*
 * API Resource Function Provisioning and Lifecycle Management
 * API to provision,manage lifecyle of, configure and activate Resource Functions (Network Services in ETSI terminology that could be composed from physical or virtual network functions)
 *
 * OpenAPI spec version: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.tmf.dsmapi.resourceFunction.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.tmf.dsmapi.resourceFunction.model.Characteristic;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Feature
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2017-06-15T01:04:08.127Z")
@Entity
public class Feature   {

     @Id
 @GeneratedValue(strategy = GenerationType.AUTO)
 private Long id = null;    
    
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("listOfCharacteristics")
  private List<Characteristic> listOfCharacteristics = new ArrayList<Characteristic>();

  public Feature name(String name) {
    this.name = name;
    return this;
  }

   /**
   *  This is the name for the feature
   * @return name
  **/
  @ApiModelProperty(required = true, value = " This is the name for the feature")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Feature listOfCharacteristics(List<Characteristic> listOfCharacteristics) {
    this.listOfCharacteristics = listOfCharacteristics;
    return this;
  }

  public Feature addListOfCharacteristicsItem(Characteristic listOfCharacteristicsItem) {
    this.listOfCharacteristics.add(listOfCharacteristicsItem);
    return this;
  }

   /**
   *  This is a list of  Resource Characteristics for a particular feature 
   * @return listOfCharacteristics
  **/
  @ApiModelProperty(required = true, value = " This is a list of  Resource Characteristics for a particular feature ")
  public List<Characteristic> getListOfCharacteristics() {
    return listOfCharacteristics;
  }

  public void setListOfCharacteristics(List<Characteristic> listOfCharacteristics) {
    this.listOfCharacteristics = listOfCharacteristics;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Feature feature = (Feature) o;
    return Objects.equals(this.name, feature.name) &&
        Objects.equals(this.listOfCharacteristics, feature.listOfCharacteristics);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, listOfCharacteristics);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Feature {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    listOfCharacteristics: ").append(toIndentedString(listOfCharacteristics)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

