/*
 * API Resource Function Provisioning and Lifecycle Management
 * API to provision,manage lifecyle of, configure and activate Resource Functions (Network Services in ETSI terminology that could be composed from physical or virtual network functions)
 *
 * OpenAPI spec version: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package org.tmf.dsmapi.resourceFunction.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModelProperty;
import org.tmf.dsmapi.resourceFunction.model.HealHealPolicy;
import org.tmf.dsmapi.resourceFunction.model.NameValuePair;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Heal
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2017-06-15T01:04:08.127Z")
@Entity
public class Heal   {
  @JsonProperty("id")
   @Id 
  @GeneratedValue(strategy = GenerationType.AUTO)
  private String id = null;

  @JsonProperty("href")
  private String href = null;

  @JsonProperty("cause")
  private String cause = null;

  /**
   * Indicates the degree of healing required
   */
  public enum DegreeOfHealingEnum {
    COMPLETE_RESTORE_TO_STATE_BEFORE_FAILURE("Complete - Restore to state before failure"),
    
    COMPLETE_HEAL_BASED_ON_LATEST_QOS_VALUES("Complete - Heal based on latest QOS values"),
    
    COMPLETE_RESTORE_TO_INSTATIATION_STATE("Complete - Restore to instatiation state"),
    
    PARTIAL("Partial");

    private String value;

    DegreeOfHealingEnum(String value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DegreeOfHealingEnum fromValue(String text) {
      for (DegreeOfHealingEnum b : DegreeOfHealingEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("degreeOfHealing")
  private DegreeOfHealingEnum degreeOfHealing = null;

  @JsonProperty("healAction")
  private String healAction = null;

  @JsonProperty("healPolicy")
  private HealHealPolicy healPolicy = null;

  @JsonProperty("startTime")
  private String startTime = null;

  @JsonProperty("additionalParms")
  private List<NameValuePair> additionalParms = new ArrayList<NameValuePair>();

  /**
   * Status of the heal operation
   */
  public enum HealStatusEnum {
    IN_PROGRESS("In Progress"),
    
    PAUSED_CONSUMER_INPUT_REQUIRED("Paused - Consumer Input Required"),
    
    PAUSED_MANUAL_INTERVENTION_REQUIRED("Paused - Manual Intervention Required");

    private String value;

    HealStatusEnum(String value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static HealStatusEnum fromValue(String text) {
      for (HealStatusEnum b : HealStatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("healStatus")
  private HealStatusEnum healStatus = null;

  public Heal id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Identifier of the Heal task resource. Required to be unique. Used in URIs as the identifier of the Heal task resource
   * @return id
  **/
  @ApiModelProperty(example = "490987", value = "Identifier of the Heal task resource. Required to be unique. Used in URIs as the identifier of the Heal task resource")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Heal href(String href) {
    this.href = href;
    return this;
  }

   /**
   * Reference to the Resource Function that needs to be healed
   * @return href
  **/
  @ApiModelProperty(example = "http://serverlocation:port/resourceFunction/17898", required = true, value = "Reference to the Resource Function that needs to be healed")
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }

  public Heal cause(String cause) {
    this.cause = cause;
    return this;
  }

   /**
   * Reason why the heal is being requested.
   * @return cause
  **/
  @ApiModelProperty(example = "SLA violation", required = true, value = "Reason why the heal is being requested.")
  public String getCause() {
    return cause;
  }

  public void setCause(String cause) {
    this.cause = cause;
  }

  public Heal degreeOfHealing(DegreeOfHealingEnum degreeOfHealing) {
    this.degreeOfHealing = degreeOfHealing;
    return this;
  }

   /**
   * Indicates the degree of healing required
   * @return degreeOfHealing
  **/
  @ApiModelProperty(required = true, value = "Indicates the degree of healing required")
  public DegreeOfHealingEnum getDegreeOfHealing() {
    return degreeOfHealing;
  }

  public void setDegreeOfHealing(DegreeOfHealingEnum degreeOfHealing) {
    this.degreeOfHealing = degreeOfHealing;
  }

  public Heal healAction(String healAction) {
    this.healAction = healAction;
    return this;
  }

   /**
   * Exact action to be taken as part of the heal process or a pointer to a script to be run
   * @return healAction
  **/
  @ApiModelProperty(example = "/conf/lab/healfast.sh", value = "Exact action to be taken as part of the heal process or a pointer to a script to be run")
  public String getHealAction() {
    return healAction;
  }

  public void setHealAction(String healAction) {
    this.healAction = healAction;
  }

  public Heal healPolicy(HealHealPolicy healPolicy) {
    this.healPolicy = healPolicy;
    return this;
  }

   /**
   * Get healPolicy
   * @return healPolicy
  **/
  @ApiModelProperty(value = "")
  public HealHealPolicy getHealPolicy() {
    return healPolicy;
  }

  public void setHealPolicy(HealHealPolicy healPolicy) {
    this.healPolicy = healPolicy;
  }

  public Heal startTime(String startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * The time when the heal action needs to commence. This allows a delay to be added
   * @return startTime
  **/
  @ApiModelProperty(example = "2017:11:7:15:53:10Z", value = "The time when the heal action needs to commence. This allows a delay to be added")
  public String getStartTime() {
    return startTime;
  }

  public void setStartTime(String startTime) {
    this.startTime = startTime;
  }

  public Heal additionalParms(List<NameValuePair> additionalParms) {
    this.additionalParms = additionalParms;
    return this;
  }

  public Heal addAdditionalParmsItem(NameValuePair additionalParmsItem) {
    this.additionalParms.add(additionalParmsItem);
    return this;
  }

   /**
   * Additional parameters to be sent to the heal action as name value pairs
   * @return additionalParms
  **/
  @ApiModelProperty(value = "Additional parameters to be sent to the heal action as name value pairs")
  public List<NameValuePair> getAdditionalParms() {
    return additionalParms;
  }

  public void setAdditionalParms(List<NameValuePair> additionalParms) {
    this.additionalParms = additionalParms;
  }

  public Heal healStatus(HealStatusEnum healStatus) {
    this.healStatus = healStatus;
    return this;
  }

   /**
   * Status of the heal operation
   * @return healStatus
  **/
  @ApiModelProperty(value = "Status of the heal operation")
  public HealStatusEnum getHealStatus() {
    return healStatus;
  }

  public void setHealStatus(HealStatusEnum healStatus) {
    this.healStatus = healStatus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Heal heal = (Heal) o;
    return Objects.equals(this.id, heal.id) &&
        Objects.equals(this.href, heal.href) &&
        Objects.equals(this.cause, heal.cause) &&
        Objects.equals(this.degreeOfHealing, heal.degreeOfHealing) &&
        Objects.equals(this.healAction, heal.healAction) &&
        Objects.equals(this.healPolicy, heal.healPolicy) &&
        Objects.equals(this.startTime, heal.startTime) &&
        Objects.equals(this.additionalParms, heal.additionalParms) &&
        Objects.equals(this.healStatus, heal.healStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, href, cause, degreeOfHealing, healAction, healPolicy, startTime, additionalParms, healStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Heal {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    cause: ").append(toIndentedString(cause)).append("\n");
    sb.append("    degreeOfHealing: ").append(toIndentedString(degreeOfHealing)).append("\n");
    sb.append("    healAction: ").append(toIndentedString(healAction)).append("\n");
    sb.append("    healPolicy: ").append(toIndentedString(healPolicy)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    additionalParms: ").append(toIndentedString(additionalParms)).append("\n");
    sb.append("    healStatus: ").append(toIndentedString(healStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

